pacman -Syu --noconfirm --needed \
  hyprland \
  kitty \
  pcmanfm \
  firefox \
  wofi \
  waybar \
  hyprpaper \
  mako \
  polkit \
  wl-clipboard \
  cliphist \
  grim \
  slurp \
  playerctl \
  brightnessctl \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  ttf-jetbrains-mono \
  ttf-font-awesome \
  nerd-fonts \
  gvfs \
  ffmpegthumbnailer \
  xdg-user-dirs \
  networkmanager \
  network-manager-applet \
  bluez \
  bluez-utils \
  blueman \
  wireplumber \
  fastfetch
